###
# curl --location --request POST 'http://localhost:9000/api/posts'
#    --header 'Accept: application/json'
#    --header 'Content-Type: application/json'
#    --data-raw '{
#        "userId": 999,
#        "title": "sunt aut fhedaaaaaccaecati excepturi optio reprehenderit",
#        "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
#    }'
POST http://localhost:9000/api/posts
Accept: application/json
Content-Type: application/json

{
  "userId": 999,
  "title": "sunt aut fhedaaaaaccaecati excepturi optio reprehenderit",
  "body": "quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto"
}

###

# curl --location --request GET 'http://localhost:9000/api/posts/1'
#--header 'Accept: application/json'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "userId": 999,
#    "title": "sunt aut fhedaaaaaccaecati excepturi optio reprehenderit",
#    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
#}'
GET http://localhost:9000/api/posts/1
Accept: application/json
Content-Type: application/json

###



